//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : AdministradorSonido.java
//  @ Date : 02/05/2021
//  @ Author : 
//
//
package adventureisland;

import java.io.File;
import java.io.IOException;
import java.util.Hashtable;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;

/**
 *
 * @author Ferreyra
 */
public class AdministradorSonido {
    private static Hashtable<String,Clip> table_sounds;
    private String musica_area[] = {"Sonidos\\Area1.wav", //0
                                    "Sonidos\\Area2.wav"}; //1
    
    private String start_end[] = {"Sonidos\\Inicio.wav", //0
                                  "Sonidos\\TodasIslas.wav", //1
                                  "Sonidos\\GameOver.wav", //2
                                  "Sonidos\\Ranking.wav"}; //3
    
    private String efectos[] = {"Sonidos\\Efectos\\1erGolpeAHuevo.wav",  //0
                                "Sonidos\\Efectos\\CaidaEnPozo.wav", //1
                                "Sonidos\\Efectos\\ChocarPiedra_MatarRomperConAdita.wav",  //2
                                "Sonidos\\Efectos\\DisparoDinoAzul.wav", //3
                                "Sonidos\\Efectos\\DisparoDinosaurioAzul.wav",  //4
                                "Sonidos\\Efectos\\DisparoDinosaurioVioleta.wav",  //5
                                "Sonidos\\Efectos\\Fruta_HuevoMartillo.wav",  //6
                                "Sonidos\\Efectos\\Hacha.wav",  //7
                                "Sonidos\\Efectos\\MuerteEnemigo.wav",  //8
                                "Sonidos\\Efectos\\MuerteHeroe.wav",  //9
                                "Sonidos\\Efectos\\ObtenerDinosaurioAzul.wav",  //10
                                "Sonidos\\Efectos\\ObtenerDinosaurioVioleta.wav",  //11
                                "Sonidos\\Efectos\\Saltar.wav",  //12
                                "Sonidos\\Efectos\\SapoSalta.wav",  //13
                                "Sonidos\\Efectos\\SumaPuntaje.wav",  //14
                                "Sonidos\\Efectos\\HeroeMuere.wav", //15
                                "Sonidos\\Efectos\\SonidoPasaje.wav" }; //16
    
    private Clip m_area1;
    private Clip m_area2;
    private Clip inicio;
    private Clip todasislas;
    private Clip gameover;
    private Clip ranking;
    private Clip efectos_clip[];
    private static AdministradorSonido instancia;
    
    private boolean act_musica = true;
    private boolean act_sonido = true;

    public AdministradorSonido(){
        try {
            table_sounds=new Hashtable<String,Clip>();
            
            m_area1=loadSound(musica_area[0]);
            table_sounds.put("Area1", m_area1);
            
            m_area2=loadSound(musica_area[1]);
            table_sounds.put("Area2", m_area2);
            
            inicio=loadSound(start_end[0]);
            table_sounds.put("Inicio", inicio);
            
            todasislas=loadSound(start_end[1]);
            table_sounds.put("TodasIslas", todasislas);
            
            gameover=loadSound(start_end[2]);
            table_sounds.put("GameOver", gameover);
            
            ranking=loadSound(start_end[3]);
            table_sounds.put("Ranking", ranking);
            
            lista_efectos();
            
        } catch (IOException ex) {
            Logger.getLogger(AdministradorSonido.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    

    private Clip loadSound(String str) throws IOException{
        try {
            Clip clip= AudioSystem.getClip();
            clip.open(AudioSystem.getAudioInputStream(new File(str)));
            return clip;
        } catch (LineUnavailableException ex) {
            Logger.getLogger(AdministradorSonido.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedAudioFileException ex) {
            Logger.getLogger(AdministradorSonido.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(AdministradorSonido.class.getName()).log(Level.SEVERE, null, ex);
        }
        return null;
    }

    public void playSonido(String strSonido,boolean flagSonido){
        if(flagSonido==true){
            (table_sounds.get(strSonido)).setFramePosition(0);
            
            (table_sounds.get(strSonido)).start();
        }else{
            (table_sounds.get(strSonido)).stop();
        }
    }
    
    
    public void pararMusica(String str){
        if((table_sounds.get(str)).isRunning()==true){
           (table_sounds.get(str)).stop();
        }
    }

    public Hashtable<String, Clip> getTable_sounds() {
        return table_sounds;
    }


    public void lista_efectos() throws IOException{
        efectos_clip = new Clip[17];
            
        efectos_clip[0]=loadSound(efectos[0]);
        table_sounds.put("1erGolpeAHuevo", efectos_clip[0]);

        efectos_clip[1]=loadSound(efectos[1]);
        table_sounds.put("CaidaEnPozo", efectos_clip[1]);

        efectos_clip[2]=loadSound(efectos[2]);
        table_sounds.put("ChocarPiedra_MatarRomperConAdita", efectos_clip[2]);

        efectos_clip[3]=loadSound(efectos[3]);
        table_sounds.put("DisparoDinoAzul", efectos_clip[3]);

        efectos_clip[4]=loadSound(efectos[4]);
        table_sounds.put("DisparoDinosaurioAzul", efectos_clip[4]);

        efectos_clip[5]=loadSound(efectos[5]);
        table_sounds.put("DisparoDinosaurioVioleta", efectos_clip[5]);

        efectos_clip[6]=loadSound(efectos[6]);
        table_sounds.put("Fruta_HuevoMartillo", efectos_clip[6]);

        efectos_clip[7]=loadSound(efectos[7]);
        table_sounds.put("Hacha", efectos_clip[7]);

        efectos_clip[8]=loadSound(efectos[8]);
        table_sounds.put("MuerteEnemigo", efectos_clip[8]);

        efectos_clip[9]=loadSound(efectos[9]);
        table_sounds.put("MuerteHeroe", efectos_clip[9]);

        efectos_clip[10]=loadSound(efectos[10]);
        table_sounds.put("ObtenerDinosaurioAzul", efectos_clip[10]);

        efectos_clip[11]=loadSound(efectos[11]);
        table_sounds.put("ObtenerDinosaurioVioleta", efectos_clip[11]);

        efectos_clip[12]=loadSound(efectos[12]);
        table_sounds.put("Saltar", efectos_clip[12]);

        efectos_clip[13]=loadSound(efectos[13]);
        table_sounds.put("SapoSalta", efectos_clip[13]);

        efectos_clip[14]=loadSound(efectos[14]);
        table_sounds.put("SumaPuntaje", efectos_clip[14]);  
        
        efectos_clip[15]=loadSound(efectos[15]);
        table_sounds.put("HeroeMuere", efectos_clip[15]);
        
        efectos_clip[16]=loadSound(efectos[16]);
        table_sounds.put("SonidoPasaje", efectos_clip[16]);
    }

    public void setact_sonido(boolean b){
        this.act_sonido = b;
    }
    
    public boolean getact_sonido(){
        return this.act_sonido;
    }
    
    public boolean getact_musica(){
        return this.act_musica;
    }
    
    public void setact_musica(int etapaJuego,int area, boolean act){
        this.act_musica = act;
        switch(etapaJuego){
            case 0:
                playSonido("Inicio", act);
                break;
            case 1:
                playSonido("TodasIslas", act);
                break;
            case 2:
                playSonido("TodasIslas", act);
                break;
            case 3:
                if(area == 0){
                    playSonido("Area1", act);
                }else if(area == 1){
                    playSonido("Area2", act);
                }
                break;
            case 6:
                playSonido("GameOver", act);
                break;
            case 7:
                playSonido("Ranking", act);                    
                break;
               
        }
    }
}