//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : BonusHabilidad.java
//  @ Date : 02/05/2021
//  @ Author : 
//
//

package adventureisland;


public class BonusHabilidad extends ObjetoGrafico implements ObjetoMovible {

    public static final int BONUS_VACIO = 0;
    public static final int BONUS_HACHA = 1;
    public static final int BONUS_CARTA = 2;
    
    public BonusHabilidad(String direccion) {
        super(direccion);
    }
    public BonusHabilidad(String direcciones[], int cantDirecciones, int numeroImagen) {
        super(direcciones, cantDirecciones, numeroImagen);
    }
	public void dar_habilidad() {
	}

    @Override
    public void update(double delta) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void movimiento() {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}

