
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : CamptosaurioAzul.java
//  @ Date : 26/05/2021
//  @ Author : 
//
//


package adventureisland;

import java.awt.Graphics2D;

public class CamptosaurioAzul extends Dinosaurio{
    
    private static String IMAGENES[] = {"recursos\\Dinosaurio\\CamptosaurioDerecha.gif", //0
                                        "recursos\\Dinosaurio\\CamptosaurioIzquierda.gif", //
                                        "recursos\\Dinosaurio\\CamptosaurioDerecha.gif", //1
                                        "recursos\\Dinosaurio\\CamptosaurioIzquierda.gif", //5
                                        "recursos\\Dinosaurio\\CamptosaurioDerecha.gif", //1
                                        "recursos\\Dinosaurio\\CamptosaurioIzquierda.gif", //5
                                        "recursos\\Dinosaurio\\CamptosaurioSaltoDerecha.png", //6
                                        "recursos\\Dinosaurio\\CamptosaurioSaltoIzquierda.png", //7
                                        "", //8
                                        "", //9
                                        "", //10
                                        "recursos\\Dinosaurio\\CamptosaurioAtacandoDerecha.png", //11
                                        "recursos\\Dinosaurio\\CamptosaurioAtacandoIzquierda.png", //12
                                        "", // 13
                                        "recursos\\Dinosaurio\\CamptosaurioProyectil.gif"}; // 14
    
    public CamptosaurioAzul() {
        super(IMAGENES, 15, 0);
        this.visible = false;
    }
    
    @Override
    public void display(Graphics2D g){
        if(delayDisparo != 0 && proyectil){
            g.drawImage(imagenes[14], (int) posXDisparo, (int) posYDisparo, sizeImg[14][0], sizeImg[14][1], null);
            posXDisparo += direccionDisparo*10;
            delayDisparo-=1;
        } else {
            proyectil = false;
            delayDisparo = DEFAULT_DELAY_DISPARO;
        }
    }
}
