//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Enemigo.java
//  @ Date : 02/05/2021
//  @ Author : 
//
//
package adventureisland;

public class Enemigo extends Personaje {

	protected int puntos;

	public Enemigo(String direccion){
            super(direccion);
	}
        
	public Enemigo(String direcciones[], int cantidadImagenes, int numeroImagen){
            super(direcciones, cantidadImagenes, numeroImagen);
	}
        
}
