//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Hacha.java
//  @ Date : 02/05/2021
//  @ Author : 
//
//


package adventureisland;

import java.awt.Graphics2D;
import java.awt.Rectangle;
import java.awt.geom.AffineTransform;

public class Hacha extends BonusHabilidad{
    private static final String HACHA[] = {"recursos\\Hacha.png", "recursos\\Hacha.GIF"};
    private boolean fueDisparada1 = false;
    private boolean fueDisparada2 = false;
    private int posX1Disparo = -1; 
    private int posY1Disparo = -1;
    private int posX2Disparo = -1; 
    private int posY2Disparo = -1;
    private int direccion1Disparo;
    private int direccion2Disparo;
    private int contadorMovimiento1 = 0;
    private int contadorMovimiento2 = 0;
    private boolean pausa = false;
    
    public Hacha() {
        super(HACHA, 2, 0);
        this.visible = false;
    }
    
    @Override
    public void display(Graphics2D g2) {
        AffineTransform old = g2.getTransform();
        if(this.fueChocado){
            this.visible = false;
            this.cambiarImagen(1);
            if(this.fueDisparada1){
                if(posY1Disparo > Escenario.POSICION_Y_PISO-20){
                    this.fueDisparada1 = false;
                    contadorMovimiento1 = 0;
                } else {
                    g2.drawImage(this.imagen,(int) this.posX1Disparo,(int) this.posY1Disparo, this.imagen.getWidth(null)*2, this.imagen.getHeight(null)*2,null);
                    posX1Disparo+=10*direccion1Disparo;
                    if(contadorMovimiento1 < 4){
                        posY1Disparo-=2;
                    } else {
                        posY1Disparo+=2;
                        if(contadorMovimiento1 > 7){
                            posY1Disparo+=2;
                        }
                    }
                    contadorMovimiento1+=1;
                }
            }    
            if(this.fueDisparada2){
                if(posY2Disparo > Escenario.POSICION_Y_PISO-20){
                    this.fueDisparada2 = false;
                    contadorMovimiento2 = 0;
                } else {
                    g2.drawImage(this.imagen,(int) this.posX2Disparo,(int) this.posY2Disparo, this.imagen.getWidth(null)*2, this.imagen.getHeight(null)*2,null);
                    posX2Disparo+=10*direccion2Disparo;
                    if(contadorMovimiento2 < 4){
                        posY2Disparo-=2;
                    } else {
                        posY2Disparo+=2;
                        if(contadorMovimiento2 > 7){
                            posY2Disparo+=2;
                        }
                    }
                    contadorMovimiento2+=1;
                }
            }
        } else {
            if(this.visible){
                g2.drawImage(this.imagen,(int) this.posX,(int) this.posY, this.imagen.getWidth(null)*2, this.imagen.getHeight(null)*2,null);
            }
        }
        g2.setTransform(old);
    }

    public boolean disparar(int posXDisparo, int posYDisparo, int direccionDisparo) {
        if(!(this.fueDisparada1)){
            this.fueDisparada1 = true;
            this.direccion1Disparo = direccionDisparo;
            this.posX1Disparo = posXDisparo;
            this.posY1Disparo = posYDisparo;
            return true;
        } else if(!(this.fueDisparada2)){
            this.fueDisparada2 = true;
            this.direccion2Disparo = direccionDisparo;
            this.posX2Disparo = posXDisparo;
            this.posY2Disparo = posYDisparo;
            return true;
        }
        return false;
    }
    
    public Rectangle[] getHachas(){
        Rectangle rHachas[] = new Rectangle[2];
        rHachas[0] = (fueDisparada1) ? new Rectangle(posX1Disparo, posY1Disparo, imagen.getWidth(null), imagen.getHeight(null)) : null;
        rHachas[1] = (fueDisparada2) ? new Rectangle(posX2Disparo, posY2Disparo, imagen.getWidth(null), imagen.getHeight(null)) : null;
        return rHachas;
    }
    
    public void setPausa(boolean b){
        pausa = b;
    }
    
}