//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ObjetoMovible.java
//  @ Date : 02/05/2021
//  @ Author : 
//
//
package adventureisland;


public interface ObjetoMovible{
    public void update(double delta);
    public void movimiento();
}