//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Pozo.java
//  @ Date : 02/05/2021
//  @ Author : 
//
//


package adventureisland;

import java.awt.Graphics2D;

public class Pozo extends Obstaculo {
    public Pozo() {
        super("");
        this.visible = true;
    }
    
    @Override
    public void display(Graphics2D g){
        g.drawRect((int) posX, (int) posY, width, height);
    }
}
